### ISSUE TITLE
충돌해서 Blink 할 때 무적 아이템 먹으면 무적 활성화가 되지 않는 현상

### ISSUE THREAD

**Issue by m-joon-ixix** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-10#137]

**Comment by wodjs2640** [comment]
@m-joon-ixix 일단 Blink시 무적아이템이 안먹어지는 버그는 수정했고, 그리고 지금 HideAndKeep할 때 OnPlayerCollision이 무한으로 호출돼서 버그가 나왔던거 같은데(오히려 버그가 안생겼던게 더 의아해졌네요) 아이템들을 플레이어 뒤로 옮겨서 해결했습니다. 근데 여전히 낮은 확률로 blink된 색 그대로 멈추는데 재현하려고 하면 재현이 안되네요..
